# Fri Jul 11 19:32:32 ICT 2025
micronaut:
  application:
    name: resources
  validation:
    enabled: true
  server:
    port: 3000
redis:
  uri: ${REDIS_URI:redis://localhost:6379}
  ssl: ${REDIS_SSL:false}
  namespace: 'centrauthz:resources'
  codec: byte-array
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
  pool:
    enabled: true
    max-active: 10
    max-idle: 5
    min-idle: 3
    max-wait: 2000ms
  timeout: 1000ms
endpoints:
  health:
    enabled: true
    sensitive: false  # Allow access without authentication
    details-visible: ANONYMOUS  # Show health details to everyone